spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/languages
    username: postgres
    password: postgres

audio:
  storage-path: generated/audio
  base-url-path: /audio

server:
  port: 8080
